# Generated by Django 5.1.1 on 2024-09-26 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_degreemodel_fieldofstudymodel_institutenamemodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JOOBModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.URLField(max_length=100, null=True)),
                ('ememployment_type', models.CharField(choices=[('full-time', 'FULL-TIME'), ('part-time', 'PART-TIME')], max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('salary', models.CharField(max_length=100, null=True)),
                ('company_namne', models.CharField(max_length=100, null=True)),
                ('job_title', models.CharField(max_length=100, null=True)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('img', models.ImageField(null=True, upload_to='media/img')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='basicinfomodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='DegreeModel',
        ),
        migrations.AlterUniqueTogether(
            name='educationmodel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='educationmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='experiencemodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='FieldOfStudyModel',
        ),
        migrations.DeleteModel(
            name='InstituteNameModel',
        ),
        migrations.RemoveField(
            model_name='interestmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='intermediatelanguagemodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='IntermediateSkillModel',
        ),
        migrations.AlterUniqueTogether(
            name='languagemodel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='languagemodel',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='skillmodel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='skillmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='BasicInfoModel',
        ),
        migrations.DeleteModel(
            name='EducationModel',
        ),
        migrations.DeleteModel(
            name='ExperienceModel',
        ),
        migrations.DeleteModel(
            name='InterestModel',
        ),
        migrations.DeleteModel(
            name='IntermediateLanguageModel',
        ),
        migrations.DeleteModel(
            name='LanguageModel',
        ),
        migrations.DeleteModel(
            name='SkillModel',
        ),
    ]
