# Generated by Django 5.1.1 on 2024-09-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_joobmodel_remove_basicinfomodel_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joobmodel',
            name='description',
            field=models.URLField(max_length=10000, null=True),
        ),
    ]
