# Generated by Django 5.1 on 2024-09-26 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_joobmodel_ememployment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='JOBAPPLYMODEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(null=True, upload_to='media/resume')),
                ('cover', models.TextField(max_length=100, null=True)),
                ('salary', models.CharField(max_length=100, null=True)),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('work_experience', models.CharField(max_length=100, null=True)),
                ('skills', models.CharField(max_length=100, null=True)),
                ('linkedin_url', models.URLField(max_length=100, null=True)),
                ('expectted_salary', models.PositiveBigIntegerField(blank=True, null=True)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.joobmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
